### ISSUE TITLE
If game map is used, yaml won't be included in Ocra

### ISSUE THREAD

**Issue by bil-bas** [ippa/chingu#12]
Yaml is only included when a map is loaded/saved, but assuming you stop Ocra from running as far as a window opening, it won't get included unless you manually include it. Best to always require it, even if it isn't needed. Doesn't really waste any time and removes this likelihood (and yaml is a standard library, so no worries there).

**Comment by ippa** [comment]
This is just how ocra works, it autoincludes gems and so on, but it's up to the user to include media/\* levels/\* etc.

**Comment by bil-bas** [comment]
Yes, but if I "require 'chingu'" then I expect that to require all the libraries that chingu will need. I'm not talking about user data, only the YAML library itself.

The standard way to run Ocra is with:

<pre><code class="ruby">  # require all my dependencies
  require 'chingu'
  require 'chipmunk'

  # Don't run the whole application when you are just building exe.
  exit if defined? Ocra 

  # Actually run my application, in normal run
  # In Chingu's case, this _might_ require new dependencies).
</code></pre>

**Comment by ippa** [comment]
Right. Hm... thinking what would be the best solution for this. I put the yaml (and rest-client / crack) requires within the game object exporter and HighScoreClass cause I figured they would only be included when they're actually used.

But I got caught with this cotcha myself when this LD, so when I ran ocra to pack my game, I actually went into the highscores to load all dependencies, which of course is a silly way.

It also feels slightly bad making rest-client and crack first class chingu dependencies.

Any suggestions?

**Comment by bil-bas** [comment]
Well, the cost of always adding YAML is virtually nothing, so that is easy to just add directly.

I agree that it doesn't make sense to make optional gems a requirement.

1) Add them as dependencies of the Chingu gem and always require them. If they aren't huge or binary gems, does it really affect anyone if they are needed?
2) Don't add them as gem dependencies and make those sub-components (so you need 'require 'chingu/HighScore'. Hmm, doesn't actually help, since you'd still have to manually add the gems (that are hidden) yourself.

Is there an absolute reason not to put gem dependencies for all those you need, though?

**Comment by ippa** [comment]
went for #1

**Comment by bil-bas** [comment]
Ah right. I was actually going to suggest
#3 Create a chingu_high_scores gem
But I guessed it would be a massive amount of effort for not much gain. Might make sense to make a chingu_physics gem in the future (that requires Chipmunk, a binary gem) since dependency could put people off if they need to go to the effort of compiling Chipmunk if they aren't using it.
