### ISSUE TITLE
Bounding boxes are too large

### ISSUE THREAD

**Issue by bil-bas** [ippa/chingu#14]
Bounding boxes are one pixel too big on right and bottom side.
Width should be "left + width - 1", not "left + width".

**Comment by ippa** [comment]
Need to get a Rect-rewrite going .. the old one can be left as RubygameRect or something.

**Comment by bil-bas** [comment]
Yeah, sound fine. I am using Chipmunk now, so I don't think I'll be using Chingu::Rect again if I can help it :$

**Comment by ippa** [comment]
fixed in http://github.com/ippa/chingu/commit/863ddc9fed0b2f53bd7a9330c1604667793d0dce
