### ISSUE TITLE
make the dependency on crack and rest-client optional

### ISSUE THREAD

**Issue by erisdev** [ippa/chingu#21]
I suspect most people won't be using the online high scores list, especially for smaller projects. Would it be possible to load `OnlineHighScoreList` or rest-client and crack on demand?

Trying to help my cousin learn Chingu and currently the dependency on rest-client is preventing Chingu loading at all. His Ubuntu installation seems to be missing `net/https.rb` and none of the advice online has actually yielded a result.

Making these dependencies optional since they're used only by a small part of the library would also be nice for people who just don't want to use them to reduce system clutter.

**Comment by ippa** [comment]
good call, I'll try to make it happen to rc3 later tonight.

**Comment by ippa** [comment]
fixed in rc3
