### ISSUE TITLE
Swig::DirectorTypeMismatchException

### ISSUE THREAD

**Issue by martinstannard** [ippa/chingu#30]
I'm getting this Exception whenever I exit a program written using Chingu or the program stops for any error.

Screenshot: https://img.skitch.com/20110617-nue4kssps1qfqepb7466ww1an9.jpg

Backtrace from the problem report:

Process:         ruby [25821]
Path:            /Users/martin/.rvm/rubies/ruby-1.9.2-p136/bin/ruby
Identifier:      ruby
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  zsh [4491]

Date/Time:       2011-06-17 21:04:01.281 +1000
OS Version:      Mac OS X 10.6.7 (10J869)
Report Version:  6

Interval Since Last Report:          78880 sec
Crashes Since Last Report:           87
Per-App Crashes Since Last Report:   87
Anonymous UUID:                      93EBC185-888E-47E1-9F88-CF462049CB36

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Application Specific Information:
abort() called

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   libSystem.B.dylib               0x95dec156 __kill + 10
1   libSystem.B.dylib               0x95dec148 kill$UNIX2003 + 32
2   libSystem.B.dylib               0x95e7e899 raise + 26
3   libSystem.B.dylib               0x95e949b8 abort + 93
4   libstdc++.6.dylib               0x901c4fda __gnu_cxx::__verbose_terminate_handler() + 433
5   libstdc++.6.dylib               0x901c317a __cxxabiv1::__terminate(void (_)()) + 10
6   libstdc++.6.dylib               0x901c31ba __cxxabiv1::__unexpected(void (_)()) + 0
7   libstdc++.6.dylib               0x901c32b8 __gxx_exception_cleanup(_Unwind_Reason_Code, _Unwind_Exception_) + 0
8   gosu.for_1_9.bundle             0x0060a2da SwigDirector_Window::needsRedraw() const + 378
9   gosu.for_1_9.bundle             0x00656ae3 Gosu::Window::Impl::doTick(Gosu::Window&) + 307
10  com.apple.Foundation            0x98abc8d4 __NSFireTimer + 141
11  com.apple.CoreFoundation        0x953d7adb __CFRunLoopRun + 8059
12  com.apple.CoreFoundation        0x953d5464 CFRunLoopRunSpecific + 452
13  com.apple.CoreFoundation        0x953d5291 CFRunLoopRunInMode + 97
14  com.apple.HIToolbox             0x949f6e04 RunCurrentEventLoopInMode + 392
15  com.apple.HIToolbox             0x949f6bb9 ReceiveNextEventCommon + 354
16  com.apple.HIToolbox             0x949f6a3e BlockUntilNextEventMatchingListInMode + 81
17  com.apple.AppKit                0x917f278d _DPSNextEvent + 847
18  com.apple.AppKit                0x917f1fce -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 156
19  com.apple.AppKit                0x917b4247 -[NSApplication run] + 821
20  gosu.for_1_9.bundle             0x0065651c Gosu::Window::show() + 284
21  gosu.for_1_9.bundle             0x00634574 _wrap_Window_show(int, unsigned long_, unsigned long) + 84
22  libruby.1.9.1.dylib             0x001758e5 call_cfunc + 581 (vm_insnhelper.c:315)

Does this look like a gosu wrapper problem or an issue with Chingu?

One strange this is I'm having the problem on one Macbook but not another that is nearly identical.

regards

Martin

**Comment by jlnr** [comment]
This problem should have been fixed with Gosu 0.7.33, have you tried updating Gosu?

**Comment by martinstannard** [comment]
Thanks Julian, that did the trick.

Martin
