### ISSUE TITLE
Weird Input Behaviour

### ISSUE THREAD

**Issue by Trebor777** [ippa/chingu#31]
Basically

:holding_left,up, right. down   works perfectly
but 
if you try 
:holding_a   ( or any letter )  it will not call the method with the same name, or any name for that matters. ( but in the case of having the same method name as the input, it will complain if it's not here, which is good and as expected )

It's just not calling the action as it should,  or not detecting the hold for that key...

**Comment by ippa** [comment]
tested it both with input = { :holding_a => :fire} and input = [ :holding_a ] syntax.. and works well here. Ruby 1.9 on win7. Does holding key A work with pure gosu? 

If you wanna see my tests check examples\example4 and examples\tests\holding_a_test.rb

**Comment by Trebor777** [comment]
Ok tried your examples, and they work fine
then retried my old code.... and now it works... weird xD
Nevermind. Thx fo rhte quick answer!
