### ISSUE TITLE
.exe of my game?

### ISSUE THREAD

**Issue by ghost** [ippa/chingu#37]
Hi, there is a way to create a .exe of my game? That is, just click on the .exe and run the game without Chingu or ruby installed. I mean something like Ocra and Gosu. I tried to create a .exe of a game in Chingu with Ocra and I get errors, not executed. And if it can, as I do? What I need?.

**Comment by ippa** [comment]
Ocra is the best way to do it, you can see my old game Gnorf for example:

https://github.com/ippa/gnorf/blob/master/start_game.rb  (The important part is the PATH-line)

and https://github.com/ippa/gnorf/blob/master/build.bat

**Comment by semaperepelitsa** [comment]
@ippa, do you know any solution for OS X? I have done [a little game](https://github.com/semaperepelitsa/am_i_alone) for Ludum Dare and provided only Windows version with OCRA

**Comment by ippa** [comment]
talk to "jlnr" on irc, #gosu @ freenode network. he's author of Gosu which Chingu builds on and he's on osx.
