### ISSUE TITLE
latest chiungu from git fails rake tests with segmentation fault

### ISSUE THREAD

**Issue by focaskater** [ippa/chingu#39]
Hello,

I'm trying to install chingu from sources on osx Lion with ruby 1.9.2p2 (installed by macports) and rake fails with a segmentation fault, can someome help me? see the message below for a detailed trace:

Chingu::GameStateManager
  initial configuration
    $window should have a game_state_manager
    should have 0 game states
  push_game_state
    should change current game state
    should keep last game state
/Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:179: [BUG] Segmentation fault
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.1.0]

-- control frame ----------
c:0052 p:0019 s:0195 b:0195 l:000194 d:000194 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:179
c:0051 p:0028 s:0191 b:0191 l:000177 d:000190 BLOCK  /Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:195
c:0050 p:---- s:0187 b:0187 l:000186 d:000186 FINISH
c:0049 p:---- s:0185 b:0185 l:000180 d:000184 IFUNC 
c:0048 p:---- s:0183 b:0183 l:000182 d:000182 CFUNC  :each
c:0047 p:---- s:0181 b:0181 l:000180 d:000180 CFUNC  :find
c:0046 p:0013 s:0178 b:0178 l:000177 d:000177 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:194
c:0045 p:0013 s:0173 b:0173 l:000172 d:000172 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/assets.rb:50
c:0044 p:0149 s:0166 b:0166 l:000165 d:000165 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/assets.rb:81
c:0043 p:0088 s:0159 b:0159 l:000158 d:000158 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/game_states/pause.rb:38
c:0042 p:---- s:0155 b:0155 l:000154 d:000154 FINISH
c:0041 p:---- s:0153 b:0153 l:000152 d:000152 CFUNC  :new
c:0040 p:0035 s:0150 b:0150 l:000149 d:000149 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/game_state_manager.rb:307
c:0039 p:0043 s:0145 b:0145 l:000144 d:000144 METHOD /Users/francescopischedda/lavoro/chingu/lib/chingu/game_state_manager.rb:148
c:0038 p:0025 s:0138 b:0138 l:000137 d:000137 METHOD /Users/francescopischedda/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/forwardable.rb:182
c:0037 p:0022 s:0133 b:0133 l:001068 d:000132 BLOCK  /Users/francescopischedda/lavoro/chingu/spec/chingu/game_state_manager_spec.rb:24
c:0036 p:---- s:0131 b:0131 l:000130 d:000130 FINISH
c:0035 p:---- s:0129 b:0129 l:000128 d:000128 CFUNC  :instance_eval
c:0034 p:0019 s:0126 b:0126 l:000125 d:000125 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:35
c:0033 p:0014 s:0122 b:0122 l:000113 d:000121 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:70
c:0032 p:---- s:0119 b:0119 l:000118 d:000118 FINISH
c:0031 p:---- s:0117 b:0117 l:000116 d:000116 CFUNC  :each
c:0030 p:0025 s:0114 b:0114 l:000113 d:000113 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:70
c:0029 p:0030 s:0110 b:0110 l:000109 d:000109 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:116
c:0028 p:0024 s:0104 b:0104 l:000095 d:000103 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:221
c:0027 p:---- s:0101 b:0101 l:000100 d:000100 FINISH
c:0026 p:---- s:0099 b:0099 l:000098 d:000098 CFUNC  :each
c:0025 p:0054 s:0096 b:0096 l:000095 d:000095 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:221
c:0024 p:0039 s:0092 b:0092 l:000091 d:000091 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:145
c:0023 p:0011 s:0089 b:0089 l:001560 d:000088 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:47
c:0022 p:0024 s:0086 b:0086 l:000085 d:000085 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:107
c:0021 p:0059 s:0082 b:0082 l:001560 d:001560 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:45
c:0020 p:0071 s:0076 b:0076 l:000065 d:000075 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:294
c:0019 p:---- s:0071 b:0071 l:000070 d:000070 FINISH
c:0018 p:---- s:0069 b:0069 l:000068 d:000068 CFUNC  :map
c:0017 p:0017 s:0066 b:0066 l:000065 d:000065 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:290
c:0016 p:0096 s:0062 b:0062 l:000061 d:000061 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:262
c:0015 p:0014 s:0055 b:0055 l:000046 d:000054 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:263
c:0014 p:---- s:0052 b:0052 l:000051 d:000051 FINISH
c:0013 p:---- s:0050 b:0050 l:000049 d:000049 CFUNC  :map
c:0012 p:0113 s:0047 b:0047 l:000046 d:000046 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:263
c:0011 p:0014 s:0040 b:0040 l:000024 d:000039 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:24
c:0010 p:---- s:0037 b:0037 l:000036 d:000036 FINISH
c:0009 p:---- s:0035 b:0035 l:000034 d:000034 CFUNC  :map
c:0008 p:0035 s:0032 b:0032 l:000024 d:000031 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:24
c:0007 p:0022 s:0029 b:0029 l:000028 d:000028 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/reporter.rb:12
c:0006 p:0113 s:0025 b:0025 l:000024 d:000024 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:21
c:0005 p:0055 s:0020 b:0020 l:000019 d:000019 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:80
c:0004 p:0101 s:0014 b:0014 l:000013 d:000013 METHOD /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:69
c:0003 p:0021 s:0007 b:0006 l:001758 d:000005 BLOCK  /Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:11
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
## c:0001 p:0000 s:0002 b:0002 l:002518 d:002518 TOP   

-- Ruby level backtrace information ----------------------------------------
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:11:in `block in autorun'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:69:in`run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:80:in `run_in_process'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:21:in`run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/reporter.rb:12:in `report'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:24:in`block in run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:24:in `map'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:24:in`block (2 levels) in run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:263:in `run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:263:in`map'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:263:in `block in run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:262:in`run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:290:in `run_examples'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:290:in`map'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:294:in `block in run_examples'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:45:in`run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:107:in `with_around_hooks'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:47:in`block in run'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example.rb:145:in `run_before_each'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:221:in`eval_before_eachs'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:221:in `each'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:221:in`block in eval_before_eachs'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:116:in `run_hook'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:70:in`run_all'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:70:in `each'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:70:in`block in run_all'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:35:in `run_in'
/Users/francescopischedda/.rvm/gems/ruby-1.9.2-p290/gems/rspec-core-2.6.4/lib/rspec/core/hooks.rb:35:in`instance_eval'
/Users/francescopischedda/lavoro/chingu/spec/chingu/game_state_manager_spec.rb:24:in `block (3 levels) in <module:Chingu>'
/Users/francescopischedda/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/forwardable.rb:182:in`push_game_state'
/Users/francescopischedda/lavoro/chingu/lib/chingu/game_state_manager.rb:148:in `push_game_state'
/Users/francescopischedda/lavoro/chingu/lib/chingu/game_state_manager.rb:307:in`game_state_instance'
/Users/francescopischedda/lavoro/chingu/lib/chingu/game_state_manager.rb:307:in `new'
/Users/francescopischedda/lavoro/chingu/lib/chingu/game_states/pause.rb:38:in`initialize'
/Users/francescopischedda/lavoro/chingu/lib/chingu/assets.rb:81:in `[]'
/Users/francescopischedda/lavoro/chingu/lib/chingu/assets.rb:50:in`autoload'
/Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:194:in `find_file'
/Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:194:in`find'
/Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:194:in `each'
/Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:195:in`block in find_file'
/Users/francescopischedda/lavoro/chingu/lib/chingu/named_resource.rb:179:in `exist?'

-- C level backtrace information -------------------------------------------

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

rake aborted!
ruby -S rspec ./spec/chingu/animation_spec.rb ./spec/chingu/assets_spec.rb ./spec/chingu/basic_game_object_spec.rb ./spec/chingu/console_spec.rb ./spec/chingu/fpscounter_spec.rb ./spec/chingu/game_object_list_spec.rb ./spec/chingu/game_object_map_spec.rb ./spec/chingu/game_object_spec.rb ./spec/chingu/game_state_manager_spec.rb ./spec/chingu/helpers/input_client_spec.rb ./spec/chingu/helpers/input_dispatcher_spec.rb ./spec/chingu/helpers/options_setter_spec.rb ./spec/chingu/inflector_spec.rb ./spec/chingu/input_spec.rb ./spec/chingu/network_spec.rb ./spec/chingu/parallax_spec.rb ./spec/chingu/text_spec.rb ./spec/chingu/window_spec.rb failed

**Comment by ippa** [comment]
I'm going to close this old issue. I personally never had access to osx for testing and I can only assume you got past this with a newer Ruby or Gosu version.

**Comment by ktec** [comment]
I get the same error, just installed chingu and ran tests and get exactly this error.

**Comment by ktec** [comment]
Using OSX Lion btw, and ruby 1.9.3-p194 with chingu-0.8.1 gem.

ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.1.0]

.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/chingu-0.8.1/lib/chingu/named_resource.rb:195: [BUG] Segmentation fault

Running the following spec:

transitional_game_state

hth
Keith

**Comment by ippa** [comment]
can you try "gem install chingu --pre" and run the tests again?
