### ISSUE TITLE
Text #width/#height give unexpected values based on factor (0.7.6.6)

### ISSUE THREAD

**Issue by bil-bas** [ippa/chingu#5]
For Text objects, #width returns a value affected by scaling factor and #height/#size returns the absolute height, unaffected by scaling. This did confuse me for a while.

For consistency with retrofied Image, could be implemented as #width (unaffected by scaling), #height/#size (as now), #screen_width (as current #width) and #screen_height (height affected by factor). Alternatively, #width and #height being the actual screen sizes and a #font_size to find the unscaled height of the font. Not at all sure which of those two methods is best though.

**Comment by ippa** [comment]
back from vacation! now width/height works exactly as GameObject, using scaling. Font-size is set with :size => 15. I think I'll release a new gem soonish :)
