### ISSUE TITLE
Error with EnterName State

### ISSUE THREAD

**Issue by Gara-Dorta** [ippa/chingu#51]
I try the game state following the example 24, and it works great. Then I decided to use it after a previous state but then I got the following error : prueba.rb:24:in 'initialize': undefined method 'push_game_state' for nil:NilClass (NoMethodError). So it seems that the this state can only be pushed by Chingu::Window and not by any other state. The code that shows the error is:

``` ruby
class Game < Chingu::Window
  def initialize
    super(800,400,false)              # leave it blank and it will be 800,600,non fullscreen
    self.input = { :escape => :exit } # exits example on Escape    
    self.caption = "Demonstration of GameStates::EnterName"
    push_game_state(Name_Select)
  end  
end

class Name_Select < Chingu::GameState
  def initialize(options = {})
    super  
    push_game_state(GameStates::EnterName.new(:callback => method(:got_name)))
  end

  def got_name(name)
    puts "Got name: #{name}"
    exit
  end    

end  
```

**Comment by ippa** [comment]
I think the error is cause you can't call push_game_state within initialize()  (cause the envorionment for the game state isn't setup properly yet). Could you try having "Name_Select < GameStates::EnterName" and take it from there?

**Comment by Gara-Dorta** [comment]
That solves the problem, thank you. 
By the way, I am sorry for confusing mine programing mistakes with chingu bugs. 
Have you ever though about creating a forum for people using your library?

**Comment by ippa** [comment]
no worries.. I don't think it's clear in the docs you can't do it that way, I should add it. I think a whole forum would be slightly too much as this point.. I might be wrong though?
