### ISSUE TITLE
load_game_objects

### ISSUE THREAD

**Issue by n0um3n4** [ippa/chingu#61]
I don't know if I'm doing something wrong but the editor works like magic. The saved yml file is like this 

---
- Tiles::Wall
   :x ...

but when I try to load the saved yml file it says: Couldn't create class 'Tiles::Wall'

I thought it might be an issue in the save/load objects code.

**Comment by ippa** [comment]
does Tiles::Wall exist in the global namespace? Is there a longer errormsg?

You're hitting this: https://github.com/ippa/chingu/blob/master/lib/chingu/helpers/game_object.rb#L77

**Comment by n0um3n4** [comment]
I think so but, again, not a pro with ruby. You can check it: https://github.com/thelastinuit/graains-

**Comment by ippa** [comment]
The code works here.. I can move around a player.. and I see one wall-tile on the screen too :). Have you installed chingu as "gem install chingu --pre" ?

**Comment by n0um3n4** [comment]
Crap! Yes I have! In fact the example works bloody great! Damn... well thanks!
FIX: I MEANT I had it installed and still it's not working. anyway, i will fix it... someday...

**Comment by ippa** [comment]
great :)
