### ISSUE TITLE
Example 7 crash with 0.8.1 version on fill_circle

### ISSUE THREAD

**Issue by MarcosX** [ippa/chingu#63]
Hi, I thinks that this is a minor issue, but it may help if anyone else has the same issue that I had while running the code for the example 7 with the latests released version (0.8.1).

The example makes a call to #fill_circle method, defined in Chingu::Helpers::GFX. But the 0.8.1 version doesn't have the code for that method, which makes it crash.

I just downloaded the latest version of the helper file and added to my local gem. When the newest version of the gem is released this won't be a problem anymore, I guess.

**Comment by ippa** [comment]
Try "gem install chingu --pre"
