### ISSUE TITLE
Edit gamestate can't seem to save an object with color set in initialize

### ISSUE THREAD

**Issue by rkachowski** [ippa/chingu#7]
The following game object causes a segfault in my ruby interpreter when trying to save an instance of it to yaml

class Building < Chingu::GameObject
  traits :bounding_box, :collision_detection
  def initialize options
    super
    @image = Gosu::Image["1x1.png"]

```
@color = 0xff808080
```

  end
end

occurs for 1.9.2 rc1 and rc2

**Comment by ippa** [comment]
0xff808080 aint a color, it's a Bignum, try with Color.new(0xff808080)
